export const url = {
  loginUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login",
  dashboardUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index",
  requestResetPasswordUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/auth/requestPasswordResetCode",
  responsResetPasswordUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/auth/sendPasswordReset",
  addEmployeeUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee",
  employeeListUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList",
  responseListEmployeeUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/pim/employees",
  postBuzzUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/buzz/posts",
  adminUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers",
  jobTitlesListUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewJobTitleList",
  payGradesListUrl:
    "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewPayGrades",
};
